### ISSUE TITLE
NullPointerException on android.view.View android.view.View.findViewById(int)

### ISSUE THREAD

**Issue by ryankwok** [rustema/peggy-meter#10]
To recreate this on physical Alcatel Onetouch 4:
1. Submit mood logs, some with text and some without text.
2. Press on list view (graph icon) - crashes
`04-26 00:21:23.740 9478-9478/io.peggyjo.peggymeter E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.peggyjo.peggymeter, PID: 9478
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference
        at io.peggyjo.peggymeter.HistoryTextFragment.renderLog(HistoryTextFragment.java:39)
        at io.peggyjo.peggymeter.HistoryTextFragment.refresh(HistoryTextFragment.java:51)
        at io.peggyjo.peggymeter.database.MoodAdapter.addEntry(MoodAdapter.java:72)
        at io.peggyjo.peggymeter.MoodControlFragment.onClick(MoodControlFragment.java:84)
        at android.view.View.performClick(View.java:6294)
        at android.view.View$PerformClick.run(View.java:24770)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)`

To recreate this on emulated Nexus 5X:
1. Submit mood logs, some with text and some without text. - graph available
2. Press on list view(graph icon) - list available
3. Press of graph view (graph icon) - "graph data unavailable"
4. Press on emoji - crash
`04-26 00:19:26.753 8002-8002/io.peggyjo.peggymeter E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.peggyjo.peggymeter, PID: 8002
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference
        at io.peggyjo.peggymeter.HistoryTextFragment.renderLog(HistoryTextFragment.java:39)
        at io.peggyjo.peggymeter.HistoryTextFragment.refresh(HistoryTextFragment.java:51)
        at io.peggyjo.peggymeter.database.MoodAdapter.addEntry(MoodAdapter.java:72)
        at io.peggyjo.peggymeter.MoodControlFragment.onClick(MoodControlFragment.java:84)
        at android.view.View.performClick(View.java:6294)
        at android.view.View$PerformClick.run(View.java:24770)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)`

**Comment by rustema** [comment]
Really weird.
Ryan would you be able to handle it?

**Comment by ryankwok** [comment]
I'm still learning the architecture, but I'll try after I finish the pagination task. This bug doesn't happen to you?

**Comment by rustema** [comment]
I haven't tried to repro it on my device (will do later tonight).
As for the pagination stuff, see what works best for you: I feel this task is easier to it could be a better start here.

**Comment by ryankwok** [comment]
I think this was fixed earlier this week, can no longer replicate this bug.
