### ISSUE TITLE
Immediate crash on Alcatel Fierce 4

### ISSUE THREAD

**Issue by ryankwok** [rustema/peggy-meter#7]
Model Number: 5056N
Android 6.0

`04-23 21:30:11.018 28325-28325/io.peggyjo.peggymeter E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.peggyjo.peggymeter, PID: 28325
    java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: DexPathList[[zip file "/data/app/io.peggyjo.peggymeter-1/base.apk", zip file "/data/app/io.peggyjo.peggymeter-1/split_lib_slice_0_apk.apk", zip file "/data/app/io.peggyjo.peggymeter-1/split_lib_slice_1_apk.apk", zip file "/data/app/io.peggyjo.peggymeter-1/split_lib_slice_2_apk.apk", zip file "/data/app/io.peggyjo.peggymeter-1/split_lib_slice_3_apk.apk", zip file "/data/app/io.peggyjo.peggymeter-1/split_lib_slice_4_apk.apk", zip file "/data/app/io.peggyjo.peggymeter-1/split_lib_slice_5_apk.apk", zip file "/data/app/io.peggyjo.peggymeter-1/split_lib_slice_6_apk.apk", zip file "/data/app/io.peggyjo.peggymeter-1/split_lib_slice_7_apk.apk", zip file "/data/app/io.peggyjo.peggymeter-1/split_lib_slice_8_apk.apk", zip file "/data/app/io.peggyjo.peggymeter-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/io.peggyjo.peggymeter-1/lib/arm, /vendor/lib, /system/lib]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:5156)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4748)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4688)
        at android.app.ActivityThread.access$1600(ActivityThread.java:150)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: DexPathList[[zip file "/data/app/io.peggyjo.peggymeter-1/base.apk", zip file "/data/app/io.peggyjo.peggymeter-1/split_lib_slice_0_apk.apk", zip file "/data/app/io.peggyjo.peggymeter-1/split_lib_slice_1_apk.apk", zip file "/data/app/io.peggyjo.peggymeter-1/split_lib_slice_2_apk.apk", zip file "/data/app/io.peggyjo.peggymeter-1/split_lib_slice_3_apk.apk", zip file "/data/app/io.peggyjo.peggymeter-1/split_lib_slice_4_apk.apk", zip file "/data/app/io.peggyjo.peggymeter-1/split_lib_slice_5_apk.apk", zip file "/data/app/io.peggyjo.peggymeter-1/split_lib_slice_6_apk.apk", zip file "/data/app/io.peggyjo.peggymeter-1/split_lib_slice_7_apk.apk", zip file "/data/app/io.peggyjo.peggymeter-1/split_lib_slice_8_apk.apk", zip file "/data/app/io.peggyjo.peggymeter-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/io.peggyjo.peggymeter-1/lib/arm, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at android.app.ActivityThread.installProvider(ActivityThread.java:5141)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4748) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4688) 
        at android.app.ActivityThread.access$1600(ActivityThread.java:150) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
        Suppressed: java.lang.ClassNotFoundException: com.google.firebase.provider.FirebaseInitProvider
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                ... 12 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available`

**Comment by ryankwok** [comment]
Negligible. Fixed when I recloned the repo.
